<?php
/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function webmaker_hive_help($path, $arg) {
  switch ($path) {
    case "admin/help#webmaker_hive":
      return '<p>' . t("Builds a CSS Hive based on contributions.") . '</p>';
      break;
  }
}
?>
